# Generated by Django 4.2.4 on 2023-08-11 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='El. paštas')),
                ('name', models.CharField(max_length=60)),
                ('surname', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='auto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('project_resume', models.CharField(max_length=256)),
                ('Gamintojas', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('Marke', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=50)),
                ('Variklis', models.CharField(blank=True, choices=[('bak', 'bak')], max_length=20)),
                ('Galia', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('Spalva', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('utl5', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('utl6', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('utl7', models.CharField(blank=True, choices=[('Acura', 'Acura'), ('Alfa Romeo', 'Alfa'), ('Audi', 'Audi'), ('Bentley', 'Bentley'), ('BMW', 'BMW'), ('Buick', 'Buick'), ('Cadillac', 'Cad'), ('Chevrolet', 'Chev'), ('Chrysler', 'Chrysler'), ('Citroen', 'Citroen'), ('Dacia', 'Dacia'), ('Dodge', 'Dodge'), ('CSS', 'CSS'), ('JS', 'Java Script'), ('DK', 'Docker'), ('DJ', 'Django'), ('JSON', 'JSON'), ('HT ', 'HTML'), ('TK ', 'TKInter'), ('SQ', 'SQlite'), ('API', 'API'), ('WS', 'Web Scraping'), ('GT', 'Git'), ('GH', 'GitHub')], max_length=20)),
                ('project_start_date', models.DateField()),
                ('project_image', models.ImageField(blank=True, upload_to='images/')),
                ('project_status', models.CharField(choices=[('K', 'Kuriamas'), ('U', 'Užbaigtas')], max_length=1)),
                ('c_remarks', models.CharField(default='-', max_length=256, verbose_name='Pastabos')),
                ('c_created_at', models.DateTimeField(auto_now_add=True)),
                ('c_updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
