# Generated by Django 4.2.4 on 2023-09-03 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_canado', '0002_user_is_anonymous_user_is_authenticated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
    ]
