# Generated by Django 4.2.4 on 2023-08-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='valandinis_ikainis',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valandinis įkainis'),
        ),
    ]
