# Generated by Django 4.2.4 on 2023-09-04 13:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_remove_car_utl6_remove_car_utl7'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('works', '0003_remove_works_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='works',
            name='car',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to='car.car', verbose_name='Automobilis'),
        ),
        migrations.AddField(
            model_name='works',
            name='darbuotojas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='works', to=settings.AUTH_USER_MODEL, verbose_name='Darbuotojas'),
        ),
    ]
