# Generated by Django 4.2.4 on 2023-09-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_works_car_works_darbuotojas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Darbo pabaigos laikas'),
        ),
        migrations.AlterField(
            model_name='works',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Darbo pradžios laikas'),
        ),
    ]
