# Generated by Django 4.2.4 on 2023-09-01 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='utl6',
        ),
        migrations.RemoveField(
            model_name='car',
            name='utl7',
        ),
    ]
